spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: su
    password: su
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672